export const facultyMembers = [
  // Page 1
  {
    id: '1',
    name: 'Adaptante, Leo',
    department: 'IT Department',
    image: '/icon-person.png',
  },
  {
    id: '2',
    name: 'De Austria, Judy',
    department: 'BA Department',
    image: '/icon-person.png',
  },
  {
    id: '3',
    name: 'Rodmark Rufino',
    department: 'TM Department',
    image: '/icon-person.png',
  },
  {
    id: '4',
    name: 'Dionisio, Edgardo',
    department: 'HM Department',
    image: '/icon-person.png',
  },
  {
    id: '5',
    name: 'Jen',
    department: 'IT Department',
    image: '/icon-person.png',
  },
  {
    id: '6',
    name: 'BK Peña',
    department: 'BA Department',
    image: '/icon-person.png',
  },
  {
    id: '7',
    name: 'Jeremiah Tablatin',
    department: 'TM Department',
    image: '/icon-person.png',
  },
  {
    id: '8',
    name: 'Ann',
    department: 'HM Department',
    image: '/icon-person.png',
  },
  {
    id: '9',
    name: 'Yulo, Frederic',
    department: 'IT Department',
    image: '/icon-person.png',
  },
  {
    id: '10',
    name: 'Darryl Pauline Nietes',
    department: 'BA Department',
    image: '/icon-person.png',
  },
  {
    id: '11',
    name: 'BK Peña',
    department: 'TM Department',
    image: '/icon-person.png',
  },
  {
    id: '12',
    name: 'Garcia, Maria',
    department: 'HM Department',
    image: '/icon-person.png',
  },
  {
    id: '13',
    name: 'Santos, Juan',
    department: 'IT Department',
    image: '/icon-person.png',
  },
  {
    id: '14',
    name: 'Reyes, Ana',
    department: 'BA Department',
    image: '/icon-person.png',
  },
  {
    id: '15',
    name: 'Cruz, Miguel',
    department: 'TM Department',
    image: '/icon-person.png',
  },

  // Page 2
  {
    id: '16',
    name: 'Lopez, Isabella',
    department: 'HM Department',
    image: '/icon-person.png',
  },
  {
    id: '17',
    name: 'Torres, Rafael',
    department: 'IT Department',
    image: '/icon-person.png',
  },
  {
    id: '18',
    name: 'Mendoza, Sofia',
    department: 'BA Department',
    image: '/icon-person.png',
  },
  {
    id: '19',
    name: 'Ramos, Gabriel',
    department: 'TM Department',
    image: '/icon-person.png',
  },
  {
    id: '20',
    name: 'Flores, Emma',
    department: 'HM Department',
    image: '/icon-person.png',
  },
  {
    id: '21',
    name: 'Rivera, Lucas',
    department: 'IT Department',
    image: '/icon-person.png',
  },
  {
    id: '22',
    name: 'Gomez, Olivia',
    department: 'BA Department',
    image: '/icon-person.png',
  },
  {
    id: '23',
    name: 'Perez, Daniel',
    department: 'TM Department',
    image: '/icon-person.png',
  },
  {
    id: '24',
    name: 'Hernandez, Mia',
    department: 'HM Department',
    image: '/icon-person.png',
  },
  {
    id: '25',
    name: 'Morales, David',
    department: 'IT Department',
    image: '/icon-person.png',
  },
  {
    id: '26',
    name: 'Dela Cruz, Sophia',
    department: 'BA Department',
    image: '/icon-person.png',
  },
  {
    id: '27',
    name: 'Martinez, Luis',
    department: 'TM Department',
    image: '/icon-person.png',
  },
  {
    id: '28',
    name: 'Rodriguez, Elena',
    department: 'HM Department',
    image: '/icon-person.png',
  },
  {
    id: '29',
    name: 'Gonzales, Marco',
    department: 'IT Department',
    image: '/icon-person.png',
  },
  {
    id: '30',
    name: 'Fernandez, Clara',
    department: 'BA Department',
    image: '/icon-person.png',
  },

  // Page 3
  {
    id: '31',
    name: 'Navarro, Antonio',
    department: 'TM Department',
    image: '/icon-person.png',
  },
  {
    id: '32',
    name: 'Reyes, Carmen',
    department: 'HM Department',
    image: '/icon-person.png',
  },
  {
    id: '33',
    name: 'Santos, Diego',
    department: 'IT Department',
    image: '/icon-person.png',
  },
  {
    id: '34',
    name: 'Castro, Luna',
    department: 'BA Department',
    image: '/icon-person.png',
  },
  {
    id: '35',
    name: 'Ortiz, Pablo',
    department: 'TM Department',
    image: '/icon-person.png',
  },
  {
    id: '36',
    name: 'Valdez, Rosa',
    department: 'HM Department',
    image: '/icon-person.png',
  },
  {
    id: '37',
    name: 'Ramirez, Felix',
    department: 'IT Department',
    image: '/icon-person.png',
  },
  {
    id: '38',
    name: 'Mercado, Diana',
    department: 'BA Department',
    image: '/icon-person.png',
  },
  {
    id: '39',
    name: 'Bautista, Oscar',
    department: 'TM Department',
    image: '/icon-person.png',
  },
];
